[config.wallpaper]
command = "swww"
arguments = [
    "img",
    "--resize", "crop",
    "--filter", "Lanczos3",
    "--fill-color", "000000",
    "--transition-fps", "60",
    "--transition-duration", "3",
    "--transition-type", "random",
    "--transition-bezier", "0.4,0.2,0.4,1.0"
]

[config.custom_colors]
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
orange = "#fab387"
blue = "#89b4fa"
cyan = "#89dceb"
magenta = "#b4befe"

[config.custom_keywords]
rounded = "16"
rounded_xs = "4"
rounded_sm = "8"
rounded_md = "12"
rounded_lg = "16"
rounded_xl = "20"
rounded_2xl = "24"
rounded_3xl = "28"

font_sans = "NotoSans-Regular"
font_serif = "NotoSerif-Regular"
font_mono = "JetBrainsMonoNerdFontMono"

[templates.waybar]
input_path = "./templates/colors.css"
output_path = "~/.config/waybar/colors.css"

[templates.swaync]
input_path = "./templates/colors.css"
output_path = "~/.config/swaync/colors.css"
post_hook = "swaync-client -rs"

[templates.alacritty]
input_path = "./templates/alacritty.toml"
output_path = "~/.config/alacritty/themes/matugen.toml"

[templates.rofi]
input_path = "./templates/rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.zathura]
input_path = "./templates/zathura"
output_path = "~/.config/zathura/colors"

[templates.imv]
input_path = "./templates/imv"
output_path = "~/.config/imv/config"

[templates.rmpc]
input_path = "./templates/rmpc-theme.ron"
output_path = "~/.config/rmpc/themes/matugen.ron"

[templates.btop]
input_path = "./templates/btop.theme"
output_path = "~/.config/btop/themes/matugen.theme"

[templates.qutebrowser]
input_path = "./templates/qutebrowser.json"
output_path = "~/.config/qutebrowser/palettes/matugen.json"
post_hook = "pgrep -x qutebrowser >/dev/null && qutebrowser ':config-source colors.py'"
