key_path = "${XDG_DATA_HOME:-$HOME/.local/share}/history/.key"
db_path = "${XDG_DATA_HOME:-$HOME/.local/share}/history/.history.db"
session_path = "${XDG_DATA_HOME:-$HOME/.local/share}/history/.session"

dialect = "us"
timezone = "local"

auto_sync = true
update_check = true
sync_frequency = "20m"
sync_address = "https://api.atuin.sh"

local_timeout = 10
network_timeout = 10
network_connect_timeout = 10

search_mode = "fuzzy"
filter_mode = "global"
search_mode_shell_up_key_binding = "fuzzy"
filter_mode_shell_up_key_binding = "global"

style = "auto"
invert = false
inline_height = 20
show_preview = false
max_preview_height = 4

show_help = true
show_tabs = false

word_jump_mode = "emacs"
ctrl_n_shortcuts = false
exit_mode = "return-original"

history_format = "{time}\t{command}\t{duration}"

cwd_filter = []
history_filter = []
secrets_filter = true

enter_accept = false
keymap_mode = "auto"

keymap_cursor = { emacs = "blink-bar", vim_insert = "blink-bar", vim_normal = "steady-block" }
prefers_reduced_motion = true

[stats]
common_subcommands = [
    "apt", "cargo", "composer", "dnf", "docker", "git", "go", "ip", "kubectl",
    "nix", "nmcli", "npm", "pecl", "pnpm", "podman", "port", "systemctl",
    "tmux", "yarn",
]

common_prefix = [
    "sudo"
]

ignored_commands = [
    "cd", "ls", "clear", "tree", "top"
]

[keys]
scroll_exits = true

[sync]
records = true
