[general]
import = ["themes/matugen.toml"]
live_config_reload = true

[font]
size = 11
normal = { family = "JetBrainsMonoNerdFont", style = "Bold" }
bold = { family = "JetBrainsMonoNerdFont", style = "ExtraBold" }
italic = { family = "JetBrainsMonoNerdFont", style = "Bold Italic" }
bold_italic = { family = "JetBrainsMonoNerdFont", style = "ExtraBold Italic" }

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
