daemonize = true
max_history = 50
primary_threshold_ms = 5000
synchronize_selection_with_clipboard = true

snippets = []
pid_file = "/run/user/1000/clipcatd.pid"
history_file_path = "/home/null/.cache/clipcat/clipcatd-history"

[log]
level = "INFO"
emit_stdout = false
emit_stderr = false
emit_journald = true

[watcher]
capture_image = true
enable_primary = true
enable_clipboard = true
enable_secondary = false
filter_text_min_length = 1
filter_image_max_size = 5242880
filter_text_max_length = 20000000
denied_text_regex_patterns = []
sensitive_x11_atoms = ["x-kde-passwordManagerHint"]

[grpc]
port = 45045
host = "127.0.0.1"
enable_http = true
enable_local_socket = true
local_socket = "/run/user/1000/clipcat/grpc.sock"

[dbus]
enable = true

[metrics]
port = 45047
enable = true
host = "127.0.0.1"

[desktop_notification]
enable = true
timeout_ms = 2000
long_plaintext_length = 2000
icon = ""
