server_endpoint = "/run/user/1000/clipcat/grpc.sock"
preview_length = 80
finder = "rofi"

[rofi]
line_length = 1000
menu_length = 30
menu_prompt = "Clipboard"
extra_arguments = ["-theme", "clipboard.rasi"]

[custom_finder]
program = "fzf"
args = []

[log]
level = "INFO"
emit_stdout = false
emit_stderr = false
emit_journald = true
