#!/usr/bin/env bash

_exists() { command -v "$1" &>/dev/null; }

_exists zoxide && alias cd="z"
_exists bat && alias cat="bat"
_exists nvim && alias vim="nvim"
_exists btop && alias top="btop"
_exists less && alias more="less"
_exists paru && alias pacman="paru"
_exists fzf && alias pgr="fzf | more"
_exists exa &&
    alias ls="eza -h --icons=auto --color=auto --group-directories-first -A" ||
    alias ls="ls -h --color=auto --group-directories-first -A"

alias dev="devault"
alias ip="ip -color=auto"
alias diff="diff --color=auto"
alias diff="diff --color=auto"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
